language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t rgvegajr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rgvegajr/docker-react npm run test

