language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t rgvegajr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rgvegajr/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  edge: "true"
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-114485820563"
  bucket_path: "Dockerreact" 
  on:
    branch: master